### ISSUE TITLE
Advanced Reservations when no hours are assigned

### ISSUE THREAD

**Issue by jetapia** [wvulibraries/RoomMe#111]
A student was able to reserve a room for many days (using some kind of automated process judging from the time stamps), including when we were closed for the spring semester-- I'm assuming because no hours were added for the spring semester yet.  All of the reservations were made from the public interface.
[hoursIssue.pdf](https://github.com/wvulibraries/RoomMe/files/701948/hoursIssue.pdf)

**Comment by MichaelRBond** [comment]
COrrect, if hours haven't been entered yet, then the system assumes open. It used to assume closed, but it was changed because evansdale needed to be able to reserve a semester out. 

There are numerous ways to prevent this already built into the system. Such as limiting the number of reservations someone can create in a time period, limiting their hours, don't allow reservations to be made more than x day in the future. 

I can't remember if there is a config option to prevent creating reservations in the past. If not, there probably should be (or, just flat out don't allow it from the public interface and only allow it from the admin interface). If its an option, its in the documentation ... i spent a good bit of time making sure all the admin stuff was at least documented in a basic way, all linked from the readme  here: https://github.com/wvulibraries/roomme

Another ting you could do, which would take, at most, 10 minutes  to implement, would be to add a rate limiting option. "Can't create more than N reservations in X minutes" add it as an option globally. I can't see that needing to be on the building or room level. 

If they can only create 5 reservations in 15 minutes, for example. just get all the reservations that user created in the last 15 minutes 900 seconds (localtime() - 900, in the sql query). if $sqlResult->rowCount() > $config_option then errorHandle::errorMsg();

**Comment by MichaelRBond** [comment]
rate limiting in this case would be more likst an abuse than the rate limiting that is already in the system, which is designed to be used for room policy. That distinction should be made clear by the name and language in the documentation.

**Comment by jetapia** [comment]
Thanks for letting me know that assuming open was the way it was configured for a reason.  Martha and I are both fine with the student reserving the rooms so quickly.  I think the solution will be just to make sure the hours for Evansdale (and any other libraries that allow reservations far into the future) have their hours up to date on the calendar.  I'll close this issue and add the tentative Fall 2017 hours to the Evansdale calendar.
